#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/libexec/resilient-awg-failover
CONFIG_DIR=/etc/resilient-awg-failover.d

start_service() {
  [ -x "$PROG" ] && [ -d "$CONFIG_DIR" ] || return 1
  found=0
  for conf in "$CONFIG_DIR"/*.conf; do
    [ -r "$conf" ] || continue
    found=1
    name="$(basename "$conf" .conf)"
    procd_open_instance "$name"
    procd_set_param command "$PROG" --config "$conf"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
  done
  [ "$found" = 1 ]
}

reload_service() {
  stop
  start
}
