#!/bin/sh /etc/rc.common
# procd service wrapper for openwrt-vpn-kit rollback watcher.

START=19
STOP=89
USE_PROCD=1

PROG=/usr/sbin/vpn-kit-rollback

start_service() {
  procd_open_instance
  procd_set_param command "$PROG" --daemon
  procd_set_param respawn 3600 5 5
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

reload_service() {
  procd_send_signal vpn-kit-rollback
}
